version: '3.8'

services:
  api:
    build: .
    ports:
      - "${PORT:-5000}:${PORT:-5000}"
    env_file:
      - .env
    environment:
      - RABBITMQ_URL=amqp://rabbitmq
      - POSTGRES_HOST=postgres_db
      - MONGO_URI=mongodb://mongo_db:27017/${POSTGRES_DB:-task_management}
    depends_on:
      - postgres_db
      - mongo_db
      - rabbitmq

  postgres_db:
    image: postgres:15-alpine
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongo_db:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq

volumes:
  pgdata:
  mongodata:
  rabbitmqdata:
